// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omljikradbklezexugfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tbGppa3JhZGJrbGV6ZXh1Z2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTc2MjAsImV4cCI6MjA2Njk5MzYyMH0.IaUXeCTN6ukFLizpgHfIFFBqLgh_LFtMrERuoasvkuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});